pull_request_rules:
  - name: post-check-migration-probe
    conditions:
      - label = vm3-migration-never
    actions:
      post_check:
        title: vm3 migration probe
        success_conditions:
          - label = vm3-migration-never

